import os
os.system(" sleep 2 && clear ")
print ("                   1nst411ing  bas1c p4ck4ge5      ")
print ("-------------------------------------------------------------------")
os.system("apt-get update && apt-get upgrade && pkg update && pkg upgrade ")
os.system("clear")
print ("                       1nst411in pyth0n      ")
print ("-------------------------------------------------------------------")
os.system("apt-get install python python2 -y && sleep 2.5 && clear ")
print ("                   1nst411ng git wget curl                ")
print ("-------------------------------------------------------------------")
os.system("apt-get install git wget curl -y && sleep 2.5 &&  clear")
print ("                        1nst411ng pifiglet                ")
print ("-------------------------------------------------------------------")
os.system("pip install pyfiglet ")
os.system("sleep 2.5 ")
os.system("clear")
os.system("sleep 3")
print ("                                                             ")
print ("                                                             ")
os.system(" echo your basic packages for running tmsfi tool is installed ")
os.system("sleep 3 ")
print ("                                                                ")
